import axios from 'axios'

const api = axios.create({ baseURL: 'http://127.0.0.1:8000' })

export const searchProducts = (data) => api.post('/api/search', data)
export const chatMessage = (data) => api.post('/api/chat', data)
export const clearChat = (sessionId) => api.delete(`/api/chat/${sessionId}`)
export const compareProducts = (data) => api.post('/api/compare', data)
export const createCart = (data) => api.post('/api/cart/create', data)
export const addToCart = (data) => api.post('/api/cart/add', data)
export const createOrder = (data) => api.post('/api/checkout/order', data)
export const createMandateOrder = (data) => api.post('/api/checkout/mandate-order', data)
export const captureS2S = (data) => api.post('/api/checkout/s2s', data)
export const verifyPayment = (data) => api.post('/api/checkout/verify', data)
export const syncShopify = (data) => api.post('/api/shopify/sync', data)
export const getOrders = (limit = 5) => api.get(`/api/shopify/orders?limit=${limit}`)
export const getLedger = () => api.get('/api/ledger')
export const clearLedger = () => api.delete('/api/ledger')
export const getRazorpayKey = () => api.get('/api/razorpay-key')
export const estimateLogistics = (data) => api.post('/api/logistics/estimate', data)
export const getProductsByIds = (data) => api.post('/api/products/by-ids', data)
export const createPaymentLink = (data) => api.post('/api/checkout/payment-link', data)
export const getPaymentLinkStatus = (plinkId) => api.get(`/api/payment-link/${plinkId}/status`)
export const cancelPaymentLink = (plinkId) => api.post(`/api/payment-link/${plinkId}/cancel`)
export const logFailover = (data) => api.post('/api/checkout/failover-log', data)
export const createIntentMandate = (data) => api.post('/api/mandate/intent', data)
export const createCartMandate = (data) => api.post('/api/mandate/cart', data)
export const getAcpFeed = () => api.get('/api/v1/acp/catalog.json')
export const getRefunds = () => api.get('/api/checkout/refunds')
export const bulkCancelPaymentLinks = () => api.post('/api/payment-links/bulk-cancel')
export const cleanStaleRescueLinks = () => api.post('/api/payment-links/clean-stale-rescue')
export const postPaymentRefund = (data) => api.post('/api/checkout/post-payment-refund', data)

